# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170804_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
